export const ragServiceEn = {
  hero: {
    subtitle: 'Permission-aware RAG in Python: hybrid search over pgvector, with the answer generated by the AI Gateway',
    description: 'A RAG service written in Python with FastAPI that turns documents into a queryable knowledge layer. It ingests the text, generates embeddings, stores them in PostgreSQL with pgvector and answers with hybrid search that joins vector similarity and full-text, fused by Reciprocal Rank Fusion. Retrieval is permission-aware: each user only finds what they are allowed to see, and the owner filter runs on both halves of the search. The answer endpoint assembles the retrieved context and delegates generation to the AI Gateway, the sister project, closing the RAG loop. Embeddings run locally via Ollama, so everything works with no API key at all.',
    role: 'Author & Developer',
    period: '2026',
    status: 'Open source · public',
  },
  overview: {
    title: 'Overview',
    stats: [
      ['pgvector', 'vector search in Postgres'],
      ['Hybrid', 'vector + full-text via RRF'],
      ['Permission', 'each user sees only theirs'],
      ['hit@3 1.0', 'on the sample eval'],
    ],
  },
  preview: {
    title: 'Preview',
    label: 'Permission-aware search: the same query returns different documents depending on who asks',
  },
  featuresTitle: 'Features',
  features: [
    {
      title: 'Hybrid search with Reciprocal Rank Fusion',
      description: 'Search combines two rankings: vector similarity by cosine, with the pgvector HNSW index, and Postgres full-text, with tsvector and a GIN index. The two rankings are fused with RRF, a simple and robust technique that sums the inverse position of each document in each list. It all happens in a single SQL with CTEs, so the fusion runs inside the database. The result captures both meaning-based and exact-word search.',
      screenshot: 'Search result with hybrid score and the source of each chunk',
      aspect: 'wide',
    },
    {
      title: 'Permission-aware retrieval',
      description: 'Each chunk stores its owner, and search filters by owner on both halves, vector and full-text. In practice, two users ask the same question and get different results: one user private document never shows up for the other. This is the governance that separates a demo RAG from one that could go to production.',
      screenshot: 'Same query, different owners, different results',
      aspect: 'wide',
    },
    {
      title: 'Ingestion with chunking and local embeddings',
      description: 'Ingestion splits the text into overlapping windows, respecting word boundaries, generates the embeddings via Ollama with the nomic-embed-text model and stores each chunk in pgvector alongside a materialized tsvector. Since the embeddings run locally, ingestion has no cost and no external API dependency.',
      screenshot: 'Ingestion response with the document and chunk count',
      aspect: 'wide',
    },
    {
      title: 'Full answer via the AI Gateway',
      description: 'The answer endpoint runs the permission-aware search, builds a prompt with the retrieved context and delegates generation to the AI Gateway. The answer comes back with the sources used, so you can audit where each claim came from. If the gateway is down, the service degrades gracefully: it returns the sources and reports the error, without breaking.',
      screenshot: 'Generated answer with the retrieved sources listed',
      aspect: 'wide',
    },
    {
      title: 'Retrieval evaluation and tests',
      description: 'An evaluation script ingests a labeled corpus, runs paraphrased queries and measures hit@k and MRR, so search quality is measured and not assumed. On the sample corpus, retrieval ranks the right document first on every query. The test suite covers chunking and prompt building without depending on a database or network.',
      screenshot: 'Eval output with hit@k and MRR per query',
      aspect: 'wide',
    },
  ],
  architecture: {
    title: 'Architecture',
    columns: [
      ['API (Python)', ['Async FastAPI + Pydantic', 'psycopg connection pool', 'Embeddings via Ollama', 'AI Gateway client', 'Schema applied on startup']],
      ['Data (Postgres)', ['pgvector: vector(768) + HNSW', 'Full-text: tsvector + GIN', 'Hybrid search with RRF in SQL', 'Owner permission filter', 'Isolated rag_demo schema']],
      ['Quality & Deploy', ['hit@k and MRR evaluation', 'Tests with pytest', 'docker-compose with pgvector', 'Dockerfile with uv', 'CI on GitHub Actions']],
    ],
  },
  diagram: {
    title: 'Flow · Hybrid search and answer',
    subtitle: 'From the question to the retrieved sources and the generated answer',
    content: `QUERY  ──►  EMBEDDING (Ollama)
   │
   ├──────────────┬──────────────┐
   ▼              ▼              │
VECTOR         FULL-TEXT        │   owner filter
(cosine,       (tsvector,       │   on both halves
 HNSW)          GIN)            │
   └──────┬───────┘             │
          ▼   RRF              ◄┘
        TOP-K
          │
          ▼
   AI GATEWAY  ──►  ANSWER + SOURCES`,
  },
  challenges: {
    title: 'Technical_Decisions',
    items: [
      ['Hybrid search inside the database', 'The vector and full-text rankings are fused with RRF in a single SQL with CTEs. Keeping the fusion in Postgres avoids pulling large lists into the application and lets the database do the work it does well.'],
      ['Permission as part of the query', 'The owner filter runs on both halves of the search, not as a filter afterwards. That way a document without permission never even competes for the ranking, which is both safer and cheaper.'],
      ['Zero cost by design', 'Embeddings run locally via Ollama, so ingestion and search have no cost. The service also accepts a paid generation provider through the AI Gateway when wanted, without changing the rest.'],
      ['Graceful degradation', 'If the generation gateway goes down, the answer endpoint still returns the retrieved sources and reports the error instead of breaking. Retrieval, which is the core, keeps working on its own.'],
    ],
  },
}
