export const tenxDevEn = {
  hero: {
    subtitle: 'AI-powered platform that turns code repositories into searchable visual libraries',
    description: 'SaaS product built from the ground up as co-founder and CTO. Users connect a GitHub repository, and the platform turns its code into an organized, searchable visual library. Under the hood, an autonomous AI agent explores the repository with real tools to list directories, read files, and create cards without manual instructions. For improvement suggestions, six models from three providers — Claude, GPT, and Gemini — analyze each card independently before their results go through a consensus process. The rest of the product supports that workflow: SSE with pub/sub for real-time progress, metered billing through the Stripe LLM Gateway, HMAC-validated GitHub webhooks, an admin moderation panel, and role-based team management. The platform later gained multi-model chat inside each card and a project task board.',
    role: 'Co-founder & Full Stack Developer',
    period: 'Jun 2025 - Present',
    status: 'Live · active',
  },
  overview: {
    title: 'Overview',
    stats: [
      ['6 LLMs', 'in consensus-based debates'],
      ['Real-time', 'sync through GitHub Webhooks'],
      ['Metered', 'billing by AI token usage'],
      ['AI Agent', 'explores repositories with tool calls'],
    ],
  },
  contribution: {
    title: 'My_Contribution',
    description: 'I developed the product in partnership with Luiz Bertucci, contributing to architecture decisions, feature implementation, and infrastructure deployment. I independently delivered several major features: AI-generated ASCII architecture diagrams, commit analysis with a persistent project history, a unified timeline combining GitHub and 10xDev events, and the in-app notification center. I later built multi-model chat inside cards, the project task board, live and shareable AI debates, and the activation-focused home experience with welcome credits. 10xDev exists to make developers more effective with AI, and we use the platform to improve itself: its suggestion engine analyzes the 10xDev codebase and proposes changes that we then implement.',
    items: [
      ['Multi-model chat inside cards', 'conversations with multiple models in one card, streamed responses, and credit balances updated in real time'],
      ['Project task board', 'per-project kanban board with draggable columns and cards, task assignees, and status filters'],
      ['Live, shareable debates', 'model responses appear live; every debate is stored by job and receives a public read-only link'],
      ['Activation-focused home', 'guided onboarding on first access and welcome credits for running AI in the first session'],
      ['UX and responsiveness validation', 'tested desktop and mobile flows, improving usability, screen states, and interaction clarity before production releases'],
      ['Orphan-file suggestions', 'detects changed files without cards during sync and suggests creating the missing cards with AI'],
      ['Notification-based access', 'project owners can approve or reject access requests directly from a notification'],
      ['Import that feels instant', 'the AI creates the first card in the initial response and opens Improvements automatically, showing value before the import ends'],
      ['New AI provider in the gateway', 'integrated the OpenAI Responses API into the agent loop and gateway routing, enabling additional OpenAI models'],
      ['AI-powered finding clustering', 'a model groups equivalent findings, with proximity-based heuristic clustering as a fallback'],
      ['Architecture diagrams', 'AI generates each card’s architecture diagram and decides whether the card is complex enough to need one'],
      ['Commit analysis', 'automated reviewer that evaluates new code before merging, categorizes issues by type and severity, and stores project history'],
      ['Project history', 'unified timeline combining GitHub commits with imports, analyses, and improvements generated by 10xDev'],
      ['In-app notifications', 'unread counter, 17 notification types across 4 levels, and progress bars for active jobs, implemented as best-effort delivery'],
      ['Always-current code', 'ensures AI analyzes the current repository state rather than an outdated imported snapshot'],
      ['AI-judged debates', 'multiple models discuss the code, a judge issues the verdict, and the history tracks resolved findings'],
      ['Docker + Azure deployment', 'built the complete Docker and Azure deployment infrastructure from scratch with automated production releases'],
      ['Import briefing', 'AI understands the codebase before organizing it, so cards are created with the correct project context'],
      ['Admin panel + analytics', 'tracks users, activity, and Stripe payment health with search, filters, and sorting'],
      ['Usage-based AI billing', 'charges for actual consumption and reports costs by period, model, and feature'],
      ['GitHub Sync', 'automatically updates the platform when GitHub code changes, processing only the affected files'],
      ['Content CMS', 'admin-managed area for organizing videos and learning materials by technology'],
      ['Telegram webhook', 'automatically notifies the team on Telegram whenever a new user signs up'],
      ['WhatsApp notifications through Z-API', 'editable templates, pre-checks for Brazilian ninth-digit ambiguity, and background delivery that never blocks sign-up'],
      ['Safe multi-user editing', 'warns the second editor instead of silently overwriting another user’s changes'],
      ['Jest test suite', 'established the Jest and React Testing Library foundation that protects AI features against regressions'],
      ['Dark/light theme system', 'consistent themes across roughly 50 screens, with a keyboard shortcut and no flash during initial load'],
    ],
  },
  preview: {
    title: 'Preview',
    alt: '10xDev home screen with credit balance, connected GitHub account, and projects',
    label: 'Home — credits, connected GitHub account, and projects',
  },
  featuresTitle: 'Features',
  features: [
    {
      title: 'Direct GitHub Integration',
      description: 'Developers connect a repository with one click. From that point on, the platform follows every update: when new code reaches GitHub, a webhook detects the changed files and reprocesses only those files rather than the entire repository. A persistent snapshot maps each file to its card, keeping incremental sync efficient even for large repositories. A concurrency limiter allows up to eight parallel GitHub API operations to prevent throttling. When sync detects changed files without cards, AI suggests creating the missing entries so the visual library stays aligned with the repository.',
      screenshots: [
        ['Project creation modal with the Connect GitHub button', 'Before connecting — GitHub authorization button'],
        ['Project creation modal after connecting, with repository selection', 'After connecting — repository selection'],
      ],
    },
    {
      title: 'AI Agent that Explores Repositories Autonomously',
      description: 'The import process does not rely on a batch script that blindly processes files. An AI agent uses real tools: list_directory to explore the structure, read_file to inspect content, search_files to find patterns, and create_card when a code section deserves its own card. It then creates a briefing card that summarizes the entire codebase. A quality supervisor detects duplicate cards, weak content, and sections that should be merged before publication.',
      screenshots: [['Automatically generated codebase briefing card', 'Automatically generated codebase briefing card']],
    },
    {
      title: 'Real-Time Agent Progress and Activity',
      description: 'During imports, every agent event reaches the frontend through SSE as it happens. Users see each tool call, a navigable file tree, and a log of created cards. Anyone joining mid-process receives a replay of the complete event buffer. Imports can be canceled at any time, with the agent stopping safely on the next iteration. The same streaming infrastructure powers Improvements, where findings appear as each model responds, and a project banner shows active import, debate, or analysis agents.',
      screenshots: [['Import modal showing progress, created cards, and files evaluated by the agent', 'Live import — progress, created cards, and evaluated files']],
    },
    {
      title: 'Project Overview: What Changed and Where',
      description: 'After import, 10xDev connects GitHub history to the cards representing the project. Users can select a period and inspect commit counts, lines changed by contributor, affected features, and analyses or improvements generated by the platform. Each feature card lists the commits and files that changed it, indicates completed reviews, and supports analyzing one or every changed card with selected models. If a branch contains files without cards, the Overview identifies them and offers to generate the missing cards with AI.',
      screenshots: [['Project Overview with period, changed lines, commits, and affected cards', 'Overview — period changes connected to project features']],
    },
    {
      title: 'Six AI Models in Judge-Guided Debate',
      description: 'Users select which models should analyze a card, and each model works independently. A judge model then evaluates their responses, identifies agreement and conflict, and assigns weight to each suggestion. Findings show their source models, consensus level, and judge. Responses stream into the debate as they arrive, while the complete history remains available for marking findings as done, dismissed, or reopened. Every debate is persisted by job and receives a public read-only link. The first imported card gets an automatic background debate, guided onboarding explains the result, and the explorer highlights cross-branch debates and single-model suggestions.',
      screenshots: [
        ['Selection of six models as analysis participants or judges', 'Analysis — selecting participants and judges'],
        ['Debate explorer showing consensus, disagreements, and a refined suggestion', 'Debate — consensus and disagreements across models'],
      ],
    },
    {
      title: 'Multi-Model Chat Inside Each Card',
      description: 'Unlike debates, which use a judge, chat lets developers talk directly to models inside a card with its linked code already in context. Responses stream progressively, and automatic scrolling pauses when the user scrolls up to review earlier content. Multiple models can participate in one thread, model selection persists between sessions, and the credit balance updates as tokens are consumed. Code responses include syntax highlighting and colored diffs.',
      screenshots: [['Chat inside a card with code context and a Claude response', 'Card chat — code and analyses are already in context']],
    },
    {
      title: 'AI-Generated ASCII Architecture Diagrams',
      description: 'Each card can generate an ASCII architecture diagram from its linked code. Before drawing, the AI decides whether the flow is complex enough to benefit from a diagram: trivial CRUD is skipped, while OAuth, webhooks, asynchronous jobs, and non-obvious cross-layer flows qualify. Diagrams follow a consistent box-and-arrow format, identify layers, and mark new, existing, or removed elements. Cards can contain multiple navigable flows. Generation is idempotent and supports retries, timeouts, and real cancellation through an AbortSignal propagated to the AI request.',
      screenshots: [['Architecture tab for an authentication card with five navigable flows and a Google Login ASCII diagram', 'AI-generated ASCII architecture diagram based on the card’s code']],
    },
    {
      title: 'AI-Powered Commit Analysis',
      description: 'Developers select two to ten commits for review. A model acts as a senior reviewer and evaluates only the new code, using patches as evidence. The result includes a concise summary and findings with category, impact-based severity, and a concrete fix of approximately ten lines. The prompt is calibrated against noise: good code returns an empty finding list rather than invented issues. Analyses are stored in project history with stable public routes, and one run can execute several models in parallel under the same job.',
      screenshots: [],
    },
    {
      title: 'Unified Project History',
      description: 'A single timeline combines GitHub activity with 10xDev activity. It includes commits, imports, commit analyses, improvement suggestions, and newly added cards, each with its source, date, and direct link. Source filters show only GitHub events, only platform events, or both side by side.',
      screenshots: [['Project history with GitHub commits and 10xDev activities filterable by source', 'Unified history — GitHub and 10xDev events']],
    },
    {
      title: 'In-App Notification Center',
      description: 'In addition to WhatsApp and Telegram alerts, the platform includes an in-app notification center with an unread counter and individual or bulk actions. Seventeen notification types across four levels cover card moderation, completed analyses, low balances, top-ups, assigned tasks, and more. Some notifications carry live progress, and project access requests can be approved or rejected without opening the members screen. Delivery is best-effort by design, so notification failures never break the primary action.',
      screenshots: [['Notification center with tasks, AI analyses, and completed imports', 'Notifications — tasks and agent activity']],
    },
    {
      title: 'Reusable Code Library',
      description: 'Code sections are organized into cards with syntax highlighting, technology filters, and real-time search. Users edit directly inside cards with debounced autosave. Each card supports multiple content tabs and an integrated diff viewer. Project categories can be reordered through drag and drop with immediate backend persistence.',
      screenshots: [
        ['Global library with active Node.js and TypeScript filters', 'Global library — active search and filters'],
        ['Open card with context tabs and highlighted TypeScript code', 'Open card — context and code in one view'],
      ],
    },
    {
      title: 'Approval Workflow and Visibility Controls',
      description: 'Every new card enters review before publication. Editing an approved card automatically returns it to pending and clears its approval fields, ensuring every change follows the same moderation process. Admins have a dedicated queue, and cards support public, unlisted, or private visibility. Users can also share cards directly and save favorites with optimistic updates.',
      screenshots: [['Global library showing pending code with approve and reject actions', 'Moderation — code awaiting approval']],
    },
    {
      title: 'Unified AI Billing and Routing through Stripe',
      description: 'Every LLM call passes through a unified proxy that routes to Anthropic, OpenAI, or Google and records usage. A credit pre-check blocks operations before they incur cost when the credit balance is insufficient. Three layers of duplicate-charge protection, five levels of rate limiting, and idempotent debits prevent overdrafts and races between concurrent calls. New users receive welcome credits, and consumption can be filtered by period, model, and feature.',
      screenshots: [
        ['Billing page with Stripe balance, summary, and recent purchases', 'Billing — balance, summary, and recent purchases'],
        ['Usage dashboard with history by feature, model, and token count', 'Usage — history by feature, model, and tokens'],
      ],
    },
    {
      title: 'Activation-Focused Home Experience',
      description: 'On first access, the home screen becomes an activation mission instead of an empty dashboard. Users are guided through connecting GitHub, importing their first repository, and opening their first debate. Welcome credits let them run AI during the first session before deciding whether to pay.',
      screenshots: [
        ['First-access home screen with a welcome mission and R$20 in credits', 'First access — welcome mission and credits'],
        ['Welcome mission modal at the GitHub connection step', 'Guided mission — connect, import, and open a debate'],
      ],
    },
    {
      title: 'Project Task Board',
      description: 'Each project includes a kanban board for managing work alongside the code. Columns and cards are draggable, with new positions saved immediately. Tasks support assignees and status filters. Reopening a completed task returns it to the first column rather than leaving it misplaced, and an activity feed reports project changes with relative timestamps.',
      screenshots: [['Kanban board with to-do, in-progress, and completed tasks', 'Task board — filters, assignees, and reorderable columns']],
    },
    {
      title: 'Learning Content CMS',
      description: 'Admins add videos using any common YouTube URL format. The system extracts the video ID and generates the thumbnail automatically. Lessons can link to a reference card, keeping instructions, commands, and code beside the video.',
      screenshots: [
        ['Tutorial catalog with YouTube thumbnails', 'Tutorial catalog'],
        ['Lesson with a linked reference card beside the video', 'Lesson — reference card beside the video'],
      ],
    },
    {
      title: 'Open-Source Full-Stack Template',
      description: 'The template turns repetitive early product decisions into a reusable foundation and connects the application’s technical base to 10xDev’s catalog of code and features.',
      screenshots: [['template-nodejs-express-next-supabase repository on GitHub', 'template-nodejs-express-next-supabase — public repository in the 10xdev-startup organization']],
    },
  ],
  templateDetails: {
    beforeLink: 'The ',
    afterLink: ' repository is published on GitHub as a public template. One click on “Use this template” creates a ready-to-use copy in the developer’s account. The structure separates ',
    middle: ' and ',
    afterPaths: ' with strict TypeScript on both sides. It also includes 39 copy-and-paste components, a three-mode sidebar, Supabase, Tailwind CSS 3, and a version-controlled engineering environment in ',
    and: ' and ',
    ending: '.',
    evolution: 'The template provides the starting point; platform cards support continued development. Developers browse the catalog, choose the next feature, and find context, commands, and reference code to adapt within a familiar architecture.',
    slogan: 'The template is the starting point. Cards show the way forward.',
    portfolioPrefix: 'The starter has its own portfolio page covering the architecture and the 39-component showcase I implemented: ',
    portfolioLink: 'view Template Node.js',
  },
  architecture: {
    title: 'Architecture',
    columns: [
      ['Frontend', ['Next.js 15 (App Router)', 'React 19 + TypeScript', 'shadcn/ui (50+ components)', 'SSE streaming (real-time progress)', 'Supabase Realtime (live import status)', 'Optimistic updates (save/unsave)', 'react-markdown + Prism', 'DnD-Kit + react-hook-form']],
      ['Backend', ['Node.js + Express + TypeScript', 'Agent loop: Claude + GPT + Gemini (6 models)', 'Stripe LLM Gateway (unified AI proxy)', 'SSE + pub/sub with buffer replay', 'GitHub App (OAuth + HMAC Webhooks)', 'Telegram Bot (activity notifications)', 'Five-layer rate limiting', 'Concurrency limiter (8 parallel operations)']],
      ['Infrastructure', ['PostgreSQL through Supabase', 'Supabase Auth (Google OAuth)', 'Docker + docker-compose (development and production)', 'Azure Container Registry + App Service', 'HMAC-SHA256 webhook security', 'Graceful shutdown (SIGTERM/SIGINT)', 'Idempotency keys (duplicate-charge protection)']],
    ],
  },
  challenges: {
    title: 'Technical_Challenges',
    items: [
      ['Multi-model AI consensus', 'Up to six models from three providers run in parallel. An AI model groups equivalent findings; if it fails, a heuristic fallback clusters by code proximity and Jaccard similarity. Best-match pairing avoids duplicate IDs. Findings reported by several models receive higher scores, while each finding’s identity uses file, line, category, and severity instead of rewritten titles, preserving done or dismissed states across runs.'],
      ['Secure real-time GitHub sync', 'Every GitHub webhook uses HMAC-SHA256 verification. A custom concurrency limiter allows up to eight parallel GitHub API operations. Persistent file-to-card mapping supports incremental sync, and the complete OAuth flow handles token exchange and GitHub App installation.'],
      ['Complex visibility and approval logic', 'CardFeatureModel combines more than 15 conditional filters covering visibility, approval status, ownership, user roles, and projects. Admins see all pending moderation items, while users see their own cards and approved public content.'],
      ['Recoverable asynchronous import pipeline', 'Repository imports can take several minutes. The pipeline includes more than ten steps, persisted progress, JSONB logs, per-file reports, graceful cancellation, and retries after partial failure.'],
      ['Metered billing with Stripe', 'Every AI call records Stripe meter events with consumed tokens. Webhooks update subscription status in real time, while idempotency keys prevent duplicate charges.'],
      ['Billing across a shared Stripe account', '10xDev shares a Stripe account with 10xMídia, so each checkout carries metadata.product and the webhook ignores events for other products. processPaymentGrant recognizes idempotency races when another processor has already credited the payment intent. Five test scenarios cover the complete flow.'],
      ['Judge hierarchy in model debates', 'A model acts as the arbiter, evaluating agreement and conflict across all responses before weighting suggestions. Contradictions produce a verdict, while each model’s reasoning remains available for audit in the debate explorer.'],
      ['Resilient ASCII architecture generation', 'Generation is idempotent, reloads current database state, and never overwrites existing diagrams. The upsert uses optimistic concurrency and handles 409 conflicts. Retries with backoff apply only to transient failures, with tool_choice fallback, timeouts, and cancellation propagated through AbortSignal.'],
      ['Calibrated, low-noise commit analysis', 'A senior AI reviewer evaluates new code from two to ten commits using patches as evidence. High severity requires proven impact, fixes must remain small, and duplicate root-cause findings are removed. Good code returns an empty list. Analyses receive stable public routes and are grouped by job.'],
      ['Anti-staleness analysis on live code', 'Before analysis, the service rehydrates card blocks with current repository content, replaces changed sections, and marks removed files. The scalability category uses the project briefing to evaluate growth bottlenecks with concrete evidence from the current code.'],
      ['Docker + Azure infrastructure from scratch', 'Multi-stage Dockerfiles, docker-compose health checks, restart policies, external volumes, and an isolated network were configured manually. Azure Container Registry stores the images, App Service hosts the production environment, and GitHub Actions deploys automatically from main.'],
    ],
  },
  diagrams: [
    {
      title: 'Flow 01 · Import and GitSync',
      subtitle: 'From a GitHub push to updated project cards',
      content: `GITHUB APP
     │  OAuth / installation token
     │
     ├── push ──► HMAC WEBHOOK ──► EXPRESS API ──► IMPORT JOB
     │                                                │
     │                                                ▼
     │                                          AGENT LOOP
     │                              list · read · search · create_card
     │                                                │
     │                                                ▼
     └──────────────────────────────────────► CARDS + SNAPSHOT
                                                      │
                                                      ▼
                                                  SUPABASE

NEXT.JS ◄── SSE + REPLAY ◄── AGENT ORCHESTRATOR ◄── job events`,
    },
    {
      title: 'Flow 02 · Analyses and debate',
      subtitle: 'One gateway serves improvements, chat, architecture, and commit reviews',
      content: `CARD / COMMITS
      │  live code + briefing + patches
      ▼
AI SERVICES ─────► STRIPE LLM GATEWAY
                         │
              ┌──────────┼──────────┐
              ▼          ▼          ▼
           CLAUDE       GPT       GEMINI
              └──────────┼──────────┘
                         ▼
                DEBATE + CONSENSUS
                         │
                         ▼
NEXT.JS ◄── SSE / NDJSON ◄── RESULTS + USAGE ──► SUPABASE

        Auth/RBAC · rate limits · idempotent debits · Docker/Azure`,
    },
  ],
}
